name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v internal/paytoken/*.go | grep -v "repository_.go" 
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
          file: ./coverage.out
          flags: tests
          name: codecov-umbrella
          yml: ./build.yml
          fail_ci_if_error: true

    - name: Go Coverage Badge
      uses: tj-actions/coverage-badge-go@v1
      with:
          filename: coverage.out
